SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, (
    SELECT SUM(S.CODE) AS CHECK_CODE FROM SKILLCODES S WHERE S.NAME IN('Python', 'C#')
) C
WHERE D.SKILL_CODE & C.CHECK_CODE != 0
ORDER BY D.ID ASC;