SELECT T.ID, T.EMAIL, T.FIRST_NAME, T.LAST_NAME FROM (
    SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME, (D.SKILL_CODE &
        (SELECT SUM(S.CODE) FROM SKILLCODES S WHERE S.NAME IN ('Python', 'C#'))
    ) AS CHECK_CODE FROM DEVELOPERS D
) T
WHERE T.CHECK_CODE != 0
ORDER BY T.ID ASC;