SELECT t.TITLE, r.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE , '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY r 
JOIN (
    SELECT b.TITLE, b.BOARD_ID FROM USED_GOODS_BOARD b WHERE YEAR(b.CREATED_DATE) = 2022 AND MONTH(b.CREATED_DATE) = 10
) t
ON r.BOARD_ID = t.BOARD_ID
ORDER BY r.CREATED_DATE ASC, t.TITLE ASC;